name: Trigger Sync
on: [push]

jobs:
  trigger_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST Request
        env:
          CICD_SERVICE_API_KEY: ${{ secrets.CICD_SERVICE_API_KEY }}
        run: |
          curl -X POST 'https://nodecomcicdservice.onrender.com/sync/trigger' \
            -H 'accept: application/json' \
            -H "x-api-key: $CICD_SERVICE_API_KEY"
