name: Trigger Sync
on: [push]

jobs:
  trigger_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST Request
        run: |
          curl -X POST https://nodecomcicdservice.onrender.com/sync/trigger-sync \
            -H "Authorization: Bearer ${{ secrets.CICD_SERVICE_API_KEY }}"
